assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: false
  test: false
instrument: CE01ISSM-MFD35-02-PRESFA000
stream:
  method: telemetered
  name: presf_abc_dcl_wave_burst
workflow_config:
  schedule: 0 0 * * *
